### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by zauberparacelsus** [mrkite/TerraFirma#60]
Since there is no linux package for the latest version of Terrafirma, I decided to try building it myself.  However, the build immediately failed, with the following output:

```
zauber@daedalusMK3:/tmp/TerraFirma-3.0.15$ debuild
 dpkg-buildpackage -rfakeroot -D -us -uc
dpkg-buildpackage: source package Terrafirma
dpkg-buildpackage: source version 3.0.15
dpkg-buildpackage: source distribution vivid
dpkg-buildpackage: source changed by Sean Kasun <sean@seancode.com>
 dpkg-source --before-build TerraFirma-3.0.15
dpkg-buildpackage: host architecture amd64
dpkg-source: error: source package name 'Terrafirma' is illegal: character 'T' not allowed
dpkg-buildpackage: error: dpkg-source --before-build TerraFirma-3.0.15 gave error exit status 2
debuild: fatal error at line 1376:
dpkg-buildpackage -rfakeroot -D -us -uc failed
```

**Comment by zauberparacelsus** [comment]
I reread the compile instructions and ran qmake, which I didn't do before.  Same problem still.

**Comment by mrkite** [comment]
Thanks.  I screwed up the debian changelog.  It should be fixed now.  I'll try to put together an official linux package tomorrow.. until then, clone the head and it should work for you.

**Comment by zauberparacelsus** [comment]
The debuild step still fails because it requires your secret key for package signing, and I don't really think those are something that you're supposed to hand out.

But, the make step builds the TerraFirma executable, so I can use that directly for now.

**Comment by mrkite** [comment]
Yeah..  the -us and -uc flags passed to debuild should skip the signing step.
